# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9d06d0f40fdf3e7d5e980aaf463e872f4e997b095b8323e732f8c1f95f7f6581f463a6e64360108ed7668f1a039b7b2025bd4ad87f267da895e106aff7d8d8

test:
  secret_key_base: 4ea269b2e1e5e65b61630fcc68f7aa8fb0c934cae1dd1d6d8c7542b9dd7cb32339e181dd708d36328aa3d694fa4e53fb4e51a58fd5fabe98708c301a309e6ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
